name: Create Release

on:
  push:    
    branches: [ main ]
    # Uncomment below if you want to trigger on tags instead
    # tags:
    #   - "v*" # Trigger on tags starting with 'v' (e.g., v1.0.0)

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This fetches all history for proper versioning

      - name: Generate Tag
        id: tag
        # Create a tag based on the date and run number if we're not triggered by a tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=v$(date +'%Y.%m.%d')-build.${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi

      - name: Zip Entire Repository
        run: zip -r fedora-setup.zip ./ -x "*.git*" ".github/*"

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: "Release ${{ steps.tag.outputs.tag }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./fedora-setup.zip
          asset_name: fedora-setup.zip
          asset_content_type: application/zip