name: autorelease

on:
  push:
    branches: [ main ]  # support both master and main branch names
    tags:
      - 'v*'  # this will trigger on any tag that starts with 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3  # updated to newer version
        with:
          fetch-depth: 0  # this ensures all tags and history are available
      
      - name: create release
        uses: cupoftea696/gh-action-auto-release@v1.0.2  # updated to newer version
        with:
          title: "release: $version"
          tag: "v$semver"
          draft: false
          regex: "/^release: v?#{semver}$/i"  # more flexible regex pattern
          prereleaseregex: "/^release: v?#{semver}-.*$/i"
        env:
          github_token: ${{ secrets.github_token }}
